### Obtener todos los docentes
GET http://localhost:3000/api/docentes

### Obtener un docente
GET http://localhost:3000/api/docentes/68dd6d86a986a458d727c3b3

### Crear un docente
POST http://localhost:3000/api/docentes
Content-Type: application/json

{
    "legajo": "61444",
    "nombre": "Joel",
    "apellido": "Arnold",
    "correo": "joelarnold@gmail.com",
    "password": "asdf"
}

### Modificar un docente (total)
PUT http://localhost:3000/api/docentes/68e17f48ba0b677f358abbda
Content-Type: application/json

{
    "legajo": "61444",
    "nombre": "Joel",
    "apellido": "Arnold",
    "correo": "joelarnold@gmail.com"
}

### Modificar un docente (parcial)
PATCH http://localhost:3000/api/docentes/68e17f48ba0b677f358abbda
Content-Type: application/json

{
    "nombre": "Diana",
    "apellido": "Martinez"
}

### Borrar un docente
DELETE http://localhost:3000/api/docentes/68e7cb33f8e4a752f55713d8