### Obtener todas las inscripciones
GET http://localhost:3000/api/inscripciones

### Obtener una inscripcion
GET http://localhost:3000/api/inscripciones/68e13ab0011816e8c3a9d16c

### Crear una inscripcion
POST http://localhost:3000/api/inscripciones
Content-Type: application/json

{
    "alumno": "68e80566981579261dc6852e",
    "consulta": "68e80ac5981579261dc68542"
}

### Modificar una inscripcion (total)
PUT http://localhost:3000/api/inscripciones/68e13a91011816e8c3a9d16b
Content-Type: application/json

{
    "alumno": "68db4f7bcb69faa5fccebea5",
    "consulta": "68df56cd3d6afc727904b7bc"
}

### Modificar una inscripcion (parcial)
PATCH http://localhost:3000/api/inscripciones/68e13ab0011816e8c3a9d16c
Content-Type: application/json

{
    "consulta": "68df2cf4a0224ddbe08a5229"
}

### Borrar una inscripcion
DELETE http://localhost:3000/api/inscripciones/68e3cd414f5e7f407b3119f4

### Por consulta
GET http://localhost:3000/api/inscripciones/byConsulta/68e80a4f981579261dc68541

### Por alumno
GET http://localhost:3000/api/inscripciones/byAlumno/68e80566981579261dc6852e

### Por alumno en horario
GET http://localhost:3000/api/inscripciones/byAlumno/68e80566981579261dc6852e/inHorario/2025-11-01T13:00:00.000Z/2025-11-01T13:45:00.000Z
