### Obtener todos los alumnos
GET http://localhost:3000/api/alumnos

### Obtener un alumno
GET http://localhost:3000/api/alumnos/68db4f77cb69faa5fccebea4

### Crear un alumno
POST http://localhost:3000/api/alumnos
Content-Type: application/json

{
    "legajo": "1",
    "nombre": "Sam",
    "apellido": "Clemens",
    "correo": "samclemens@gmail.com"
}

### Modificar un alumno (total)
PUT http://localhost:3000/api/alumnos/68e1461e6b8e442bfe1df0f8
Content-Type: application/json

{
    "legajo": "2",
    "nombre": "John",
    "apellido": "Doe",
    "correo": "johndoe@gmail.com"
}

### Modificar un alumno (parcial)
PATCH http://localhost:3000/api/alumnos/68e1461e6b8e442bfe1df0f8
Content-Type: application/json

{
    "nombre": "Mark",
    "apellido": "Twain"
}

### Borrar un alumno
DELETE http://localhost:3000/api/alumnos/68e144f400f67f8a414cd946