### Obtener todos los alumnos
GET http://localhost:3000/api/alumnos

### Obtener un alumno
GET http://localhost:3000/api/alumnos/68db4f77cb69faa5fccebea4

### Crear un alumno
POST http://localhost:3000/api/alumnos
Content-Type: application/json

{
    "legajo": "51367",
    "nombre": "Nicolás",
    "apellido": "Gallegos",
    "correo": "ngabrielgallegos@gmail.com",
    "password": "asd123"
}

### Modificar un alumno (total)
PUT http://localhost:3000/api/alumnos/68e3c236fe1fd606fd1e4735
Content-Type: application/json

{
    "legajo": "51367",
    "nombre": "John",
    "apellido": "Doe",
    "correo": "johndoe@gmail.com"
}

### Modificar un alumno (parcial)
PATCH http://localhost:3000/api/alumnos/68db4f7bcb69faa5fccebea5
Content-Type: application/json

{
    "password": "asd123"
}

### Borrar un alumno
DELETE http://localhost:3000/api/alumnos/68e804c2981579261dc6852c

### ----- Peticiones especiales -----

### Obtener un alumno por su correo
GET http://localhost:3000/api/alumnos/byCorreo/samclemens%40gmail.com

### Obtener todos los alumnos de una consulta
GET http://localhost:3000/api/alumnos/byConsulta/68df56cd3d6afc727904b7bc