### Obtener todos los alumnos
GET http://localhost:3000/api/alumnos

### Obtener un alumno
GET http://localhost:3000/api/alumnos/1

### Crear un alumno
POST http://localhost:3000/api/alumnos
Content-Type: application/json

{
    "nombre": "Olivia",
    "apellido": "Frías",
    "correo": "friasolivia@gmail.com"
}

### Modificar un alumno (total)
PUT http://localhost:3000/api/alumnos/bcff2a7b-b199-4f3b-9a92-fcbd1d250ee1
Content-Type: application/json

{
    "nombre": "Matías",
    "apellido": "Sione",
    "correo": "sionematias@gmail.com"
}

### Modificar un alumno (parcial)
PATCH http://localhost:3000/api/alumnos/bcff2a7b-b199-4f3b-9a92-fcbd1d250ee1
Content-Type: application/json

{
    "nombre": "Francisco",
    "apellido": "Juarez"
}